- name: Install Docker Latest Ubuntu
  hosts:
    - server
  become: True
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    
    - name: install initial packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
    
    - name: Create directory /etc/apt/keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"


    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Add docker apt repository
      apt_repository:
        repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present

    - name: apt update
      apt:
        update_cache: yes

    - name: docker install
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: create docker group
      group:
        name: docker
        state: present

    - name: add user to docker group
      user:
        name: yukih
        groups: docker
        append: yes

    - name: enable docker daemon
      shell: systemctl enable docker

    - name: docker restart
      shell: systemctl restart docker
